### ISSUE TITLE
Multiple bids with same price

### ISSUE THREAD

**Issue by DrrMrr** [JulyIGHOR/QtBitcoinTrader#211]
Hi,

Somethimes is first bid executed two times. I've noticed only at first bid. I always generate n bids and the lowest is sometimes executed 2 times.

I'm trading on Bitfinex and trading pair is USD/BTC. Can you please check in your code why this is happening.

![image](https://user-images.githubusercontent.com/174676/32910518-c5a13cbc-cb09-11e7-90ba-710ae2e98c15.png)

![image](https://user-images.githubusercontent.com/174676/32910525-c916cff6-cb09-11e7-9e44-46bd872b0023.png)

Thank you and best regards
Damjan

**Comment by JulyIGHOR** [comment]
We can't reproduce this issue, it looks like duplicated items is just visual bug.
Can you confirm that there is no duplicated transaction on website trade history?

**Comment by DrrMrr** [comment]
It can be. Because of Bitcoin price rising in recent weeks, I'm currently using different approach with only one bid. If I notice that again, I will reopen this "issue".

**Comment by DrrMrr** [comment]
Hi Ighor,

Happy new year 2018 and all the best in coming year.

I'm reopening this ticket with more info. Below is an image where two buys where executed, but only one was in my open order. Can you please check that again?

![slika](https://user-images.githubusercontent.com/174676/34466922-bc8c506e-eee3-11e7-8bdf-0f246abe5af5.png)
[Trader - debug.txt](https://github.com/JulyIGHOR/QtBitcoinTrader/files/1595836/Trader.-.debug.txt)

Best regards
Damjan

**Comment by JulyIGHOR** [comment]
According to log, there was only one command to buy at this price

Buy: , "symbol": "iotbtc", "amount": "6.05", "price": "0.00026116", "exchange": "all", "side": "buy", "type": "exchange limit"

As you can see amount requested was 6.05, so it have been successfully placed in order book.
Next someone bought many pieces at market price of amount 0.00157905
So you bought two pieces. There is no bug in duplicated commands, because it filtered by API feature called nonce.
